{
 "title": "Edge Command, Control and Communications",
 "tags": [ "sandbox" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_organizedtablestats{table=\"DEVICE_MESSAGES\"}",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Upstream / Downstream lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"powercostats\",EVENT_NAME=\"lagms0\"}",
     "legendFormat": "Windpower Inc Lag (MS)"
    },
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"powercostats\",EVENT_NAME=\"lagms1\"}",
     "legendFormat": "Giant Hamster Lag (MS)"
    },
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"devicestats\",EVENT_NAME=\"lagms1\"}",
     "legendFormat": "Segment 1 Lag"
    },
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"devicestats\",EVENT_NAME=\"lagms0\"}",
     "legendFormat": "Segment 0 Lag"
    }
   ]
  },
  {
   "title": "System",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (procedure)  (irate(voltdbbl_procedureprofile{measuretype=\"invocations\",procedure=\"edgeprocs.SendMessageDownstream\"}[1m]) > 0)",
     "legendFormat": "Downstream Messages Sent Per Second"
    },
    {
     "expr": "avg by (procedure)  (irate(voltdbbl_procedureprofile{measuretype=\"invocations\",procedure=\"edgeprocs.SendMessageUpstream\"}[1m]) > 0)",
     "legendFormat": "Upstream Messages Received Per Second"
    }
   ]
  },
  {
   "title": "Messages In Flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_bl_transaction_status{STATUS_CODE=\"MIF\"}",
     "legendFormat": "Messages In Flight"
    }
   ]
  },
  {
   "title": "Windpower, inc Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"powercostats\",EVENT_NAME=\"downstreamSent0\"}",
     "legendFormat": "Messages Downstream per second"
    },
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"powercostats\",EVENT_NAME=\"upstreamRcd0\"}",
     "legendFormat": "Messages Upstream per second"
    }
   ]
  },
  {
   "title": "Giant Hamster Wheel Power Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"powercostats\",EVENT_NAME=\"downstreamSent1\"}",
     "legendFormat": "Messages Downstream per second"
    },
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"powercostats\",EVENT_NAME=\"upstreamRcd1\"}",
     "legendFormat": "Messages Upstream per second"
    }
   ]
  },
  {
   "title": "Segment 0 Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"devicestats\",EVENT_NAME=\"downstreamRecd0\"}",
     "legendFormat": "Messages Downstream per second"
    },
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"devicestats\",EVENT_NAME=\"upstreamSent0\"}",
     "legendFormat": "Messages Upstream per second"
    }
   ]
  },
  {
   "title": "Segment 1 Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"devicestats\",EVENT_NAME=\"downstreamRecd1\"}",
     "legendFormat": "Messages Downstream per second"
    },
    {
     "expr": "voltdbbl_edge_bl_stats{EVENT_TYPE=\"devicestats\",EVENT_NAME=\"upstreamSent1\"}",
     "legendFormat": "Messages Upstream per second"
    }
   ]
  },
  {
   "title": "Message Disk Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)  (voltdb_topic_on_disk_bytes{topic=\"error_topic\"})  ",
     "legendFormat": "Errors Topic"
    },
    {
     "expr": "sum by (topic)  (voltdb_topic_on_disk_bytes{topic=\"powerco_0_topic\"})  ",
     "legendFormat": "Messages for Windpower, Inc"
    },
    {
     "expr": "sum by (topic)  (voltdb_topic_on_disk_bytes{topic=\"powerco_1_topic\"})  ",
     "legendFormat": "Messages for Giant Hamster Power"
    },
    {
     "expr": "sum by (topic)  (voltdb_topic_on_disk_bytes{topic=\"segment_0_topic\"})  ",
     "legendFormat": "Messages for segment 0"
    },
    {
     "expr": "sum by (topic)  (voltdb_topic_on_disk_bytes{topic=\"segment_1_topic\"})  ",
     "legendFormat": "Messages for segment 1"
    }
   ]
  }
 ]
}